version: "3.8"
services:
  mongodb:
    image : mongo:5.0.3
    container_name: MongoDBLocal
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
