version: "3.8"
services:
  service:
    image: example-async-mongodb:latest
#    image: luketn/example-async-mongodb:latest
    container_name: ExampleAsyncMongoDBVertXService
    ports:
      - 9090:9090
    environment:
      - HTTP_PORT=9090
      - CONNECTION_STRING=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image : mongo:5.0.3
    container_name: MongoDBLocal
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017
